---
- name: Install Shiny package
  command: su - -c "R -e \"install.packages('shiny', repos='http://cran.rstudio.com/')\""

- name: Download Shiny
  get_url: url=http://download3.rstudio.org/ubuntu-12.04/x86_64/shiny-server-1.3.0.403-amd64.deb dest=/tmp/shiny.deb

- name: Install Shiny
  command: gdebi /tmp/shiny.deb -n

- name: Install Shiny packages
  command: sudo su - -c "R -e \"library(devtools); install_github('{{ item }}')\""
  with_items:
    - rstudio/rmarkdown
    - daattali/shinyjs